[package]
name = "soap-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soap = "0.0.1"
# xml = "0.8.20"
xml-rs = "0.8.20"
